// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserCrudService_GetListUser_FullMethodName = "/user.UserCrudService/GetListUser"
)

// UserCrudServiceClient is the client API for UserCrudService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserCrudServiceClient interface {
	GetListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error)
}

type userCrudServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserCrudServiceClient(cc grpc.ClientConnInterface) UserCrudServiceClient {
	return &userCrudServiceClient{cc}
}

func (c *userCrudServiceClient) GetListUser(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserResponse)
	err := c.cc.Invoke(ctx, UserCrudService_GetListUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserCrudServiceServer is the server API for UserCrudService service.
// All implementations must embed UnimplementedUserCrudServiceServer
// for forward compatibility.
type UserCrudServiceServer interface {
	GetListUser(context.Context, *ListUserRequest) (*ListUserResponse, error)
	mustEmbedUnimplementedUserCrudServiceServer()
}

// UnimplementedUserCrudServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserCrudServiceServer struct{}

func (UnimplementedUserCrudServiceServer) GetListUser(context.Context, *ListUserRequest) (*ListUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetListUser not implemented")
}
func (UnimplementedUserCrudServiceServer) mustEmbedUnimplementedUserCrudServiceServer() {}
func (UnimplementedUserCrudServiceServer) testEmbeddedByValue()                         {}

// UnsafeUserCrudServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserCrudServiceServer will
// result in compilation errors.
type UnsafeUserCrudServiceServer interface {
	mustEmbedUnimplementedUserCrudServiceServer()
}

func RegisterUserCrudServiceServer(s grpc.ServiceRegistrar, srv UserCrudServiceServer) {
	// If the following call panics, it indicates UnimplementedUserCrudServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserCrudService_ServiceDesc, srv)
}

func _UserCrudService_GetListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCrudServiceServer).GetListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCrudService_GetListUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCrudServiceServer).GetListUser(ctx, req.(*ListUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserCrudService_ServiceDesc is the grpc.ServiceDesc for UserCrudService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserCrudService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserCrudService",
	HandlerType: (*UserCrudServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetListUser",
			Handler:    _UserCrudService_GetListUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
